#cloud-config
users:
  - name: gaetan
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/sh
    ssh_authorized_keys:
      
      
packages:
  - nginx

runcmd:
  - setup-service nginx
  - rc-service nginx start
  - echo "<h1>TP MicroStack - Bienvenue chez GaÃ«tan</h1>" > /var/www/localhost/htdocs/index.html