#cloud-config
users:
  - name: gaetan
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/sh
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOjEQKDCHy7xujuPFRXv6hCxYIfQ6TkxzeGPRWPy+fKE gaetan@tp-openstack

packages:
  - nginx

runcmd:
  - setup-service nginx
  - rc-service nginx start
  - echo "<h1>TP MicroStack - Bienvenue chez GaÃ«tan</h1>" > /var/www/localhost/htdocs/index.html