name: Deploy Alpine VM to MicroStack

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create VM on OpenStack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: "Default"
          OS_PROJECT_DOMAIN_NAME: "Default"
        run: |                 
          sudo /snap/bin/microstack.openstack server create \
            --image "Alpine" \
            --flavor Minus \
            --network LAN-LABO \
            --security-group SG-LABO \
            --user-data /var/snap/microstack/common/var/cloud-init.yaml \
            --key-name ma-cle-openstack \
            VM-Alpine-Gaetan